WebBlog/WebBlog/Areas/Admin/Models/Category/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WebBlog.Site.Resources;

namespace WebBlog.Site.Areas.Admin.Models.Category
{
    public class CategoryViewModel
    {
        [Required]
        [Display(ShortName = "CategoryName", ResourceType = typeof(Strings))]
        public string CategoryName { get; set; }

        public Guid CategoryId { get; set; }
    }
}

WebBlog/WebBlog/Areas/Admin/Models/Tag/TagViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using WebBlog.Entities;
using WebBlog.Site.Resources;

namespace WebBlog.Site.Areas.Admin.Models.Tag
{
    public class TagViewModel
    {
        [Required]
        [Display(ShortName = "TagName", ResourceType = typeof(Strings))]
        public string TagName { get; set; }

        public Guid TagId { get; set; }
    }
}

WebBlog/WebBlog/Models/ErrorViewModel.cs
using System;

namespace WebBlog.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebBlog/WebBlog/Areas/Admin/Pages/Categories/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebBlog.Entities;
using WebBlog.Service;
using WebBlog.Site.Areas.Admin.Models.Category;
using WebBlog.Site.Resources;

namespace WebBlog.Site.Areas.Admin.Pages.Categories
{
    public class IndexModel : PageModel
    {
        private readonly IMapper _mapper;
        private readonly ICategoryService _categoryService;

        [BindProperty]
        public CategoryViewModel CategoryModel { get; set; }

        public IList<CategoryViewModel> Categories { get; set; }

        public IndexModel(IMapper mapper, ICategoryService categoryService)
        {
            _mapper = mapper;
            _categoryService = categoryService;
        }

        public IActionResult OnGet()
        {
            Categories = _mapper.Map<IList<CategoryViewModel>>(_categoryService.GetAll());
           return Page();
        }

        public IActionResult OnPostAdd()
        {
            Categories = _mapper.Map<IList<CategoryViewModel>>(_categoryService.GetAll());
            if (!ModelState.IsValid)
            {
                return Page();
            }
            else if (_categoryService.Exist(CategoryModel.CategoryName))
            {
                ModelState.AddModelError($"{nameof(CategoryModel)}.{nameof(CategoryModel.CategoryName)}",
                    string.Format(Strings.Error_HasExisted, Strings.CategoryName));

                return Page();
            }


            _categoryService.Insert(CategoryModel.CategoryName);

            return RedirectToPage("Index");
        }

        [HttpPost]
        public IActionResult OnPostEdit()
        {
            string errors = string.Empty;
            if (!ModelState.IsValid)
            {
                errors = string.Join("; ", ModelState.Values
                                        .SelectMany(x => x.Errors)
                                        .Select(x => x.ErrorMessage));
            }
            else if (_categoryService.Exist(CategoryModel.CategoryName, CategoryModel.CategoryId))
            {
                errors = string.Format(Strings.Error_HasExisted, Strings.CategoryName);
            }

            if (!string.IsNullOrEmpty(errors))
            {
                return BadRequest(errors);
            }

            var entity = _mapper.Map<Category>(CategoryModel);
            _categoryService.Update(entity);

            return new OkResult();
        }


        public IActionResult OnGetDelete(Guid id)
        {
            _categoryService.Delete(id);
            return RedirectToPage();
        }
    }
}

WebBlog/WebBlog/Areas/Admin/Pages/Dashboard/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebBlog.Site.Areas.Admin.Pages.Dashboard
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebBlog/WebBlog/Areas/Admin/Pages/Login/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebBlog.Site.Areas.Admin.Pages.Login
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebBlog/WebBlog/Areas/Admin/Pages/Tags/Index.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using WebBlog.Entities;
using WebBlog.Service;
using WebBlog.Site.Areas.Admin.Models.Tag;
using WebBlog.Site.Resources;

namespace WebBlog.Site.Areas.Admin.Pages.Tags
{
    public class IndexModel : PageModel
    {
        private readonly ITagService _tagService;
        private readonly IMapper _mapper;

        [BindProperty]
        public TagViewModel TagModel { get; set; }
        public IList<TagViewModel> Tags { get; set; }

        public IndexModel(ITagService tagService, IMapper mapper)
        {
            _tagService = tagService;
            _mapper = mapper;
        }

        public IActionResult OnGet()
        {
            Tags = _mapper.Map<IList<TagViewModel>>(_tagService.GetAll());
            return Page();
        }

        public IActionResult OnPostAdd()
        {
            Tags = _mapper.Map<IList<TagViewModel>>(_tagService.GetAll());
            if (!ModelState.IsValid)
            {
                return Page();
            }
            else if (_tagService.Exist(TagModel.TagName))
            {
                ModelState.AddModelError($"{nameof(TagModel)}.{nameof(TagModel.TagName)}", 
                    string.Format(Strings.Error_HasExisted, Strings.TagName));

                return Page();
            }


            _tagService.Insert(TagModel.TagName);

            return RedirectToPage("Index");
        }

        [HttpPost]
        public IActionResult OnPostEdit()
        {
            string errors = string.Empty;
            if (!ModelState.IsValid)
            {
                errors = string.Join("; ", ModelState.Values
                                        .SelectMany(x => x.Errors)
                                        .Select(x => x.ErrorMessage));
            }
            else if (_tagService.Exist(TagModel.TagName, TagModel.TagId))
            {
                errors = string.Format(Strings.Error_HasExisted, Strings.TagName);
            }

            if (!string.IsNullOrEmpty(errors))
            {
                return BadRequest(errors);
            }

            var entity = _mapper.Map<Tag>(TagModel);
            _tagService.Update(entity);

            return new OkResult();
        }

        public IActionResult OnGetDelete(Guid id)
        {
            _tagService.Delete(id);
            return RedirectToPage();
        }
    }
}

WebBlog/WebBlog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebBlog.Models;

namespace WebBlog.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebBlog/WebBlog/Areas/Admin/Pages/Categories/Index.cshtml
@page
@model IndexModel
@{
}
<style>
    form[editmode="false"] .jqEditMode,
    form[editmode="true"] .jqViewMode {
        display: none !important;
    }
</style>


<div class="col-sm-6">
    <span class="text-danger" id="errorMessages"></span>
    @foreach (var item in Model.Categories)
    {
        <div class="form-group has-feedback">
            <form asp-page-handler="Edit" method="post" editMode="false" onsubmit="return onSubmit(this)">

                <div class="input-group">
                    <input type="hidden" asp-for="@item.CategoryId" name="CategoryModel.CategoryId" />
                    <input type="text" asp-for="@item.CategoryName" name="CategoryModel.CategoryName" id="@item.CategoryId" asp-value="@item.CategoryName" class="form-control" readonly/>

                    <div class="input-group-btn jqViewMode">
                        <a class="btn btn-primary" onclick="onEditForm('#@item.CategoryId')">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                        <a asp-page-handler="Delete" asp-route-id="@item.CategoryId" class="btn btn-danger" onclick="return confirmDelete(this)">
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    </div>

                    <div class="input-group-btn jqEditMode">
                        <button class="btn btn-primary">
                            <span type="submit" class="glyphicon">@Strings.Save</span>
                        </button>
                        <a class="btn btn-default" onclick="onCancelForm('#@item.CategoryId')">
                            <span type="submit" class="glyphicon">@Strings.Cancel</span>
                        </a>
                    </div>
                </div>

            </form>
        </div>
    }



    <br />
    <form class="row" asp-page-handler="Add" method="post">
        <div class="col-sm-9">
            <input type="text" asp-for="@Model.CategoryModel.CategoryName" class="form-control" placeholder="Enter category">
            <span class="text-danger" asp-validation-for="@Model.CategoryModel.CategoryName"></span>
        </div>
        <button type="submit" id="submitTag" class="btn btn-primary col-sm-3">@Strings.AddNew</button>
    </form>
</div>
<div class="clearfix" />

@section Scripts {
    <script>
        function onCancelForm(elementId) {
            // Set back to value before edit
            $(elementId).val($(elementId).attr('asp-value'));
            $(elementId).attr('readonly', true);
            // clear error message if it occurs
            $('#errorMessages').text('');

            $(elementId).parents('form').attr('editMode', false)
        }

        function onEditForm(elementId) {
            $(elementId).removeAttr('readonly');
            $(elementId).parents('form').attr('editMode', true)
        }

        function onSubmit(e) {
            $.post('/Admin/Categories?handler=Edit', $(e).serialize())
                .done(function () {
                    window.location.reload();
                }).fail(function (xhr) {
                    $('#errorMessages').text(xhr.responseText);
                })

            return false;
        }
    </script>

}

WebBlog/WebBlog/Areas/Admin/Pages/Components/Breadcrumb/Default.cshtml
<h1>
    General Form Elements
    <small>Preview</small>
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="#">Forms</a></li>
    <li class="active">General Elements</li>
</ol>

WebBlog/WebBlog/Areas/Admin/Pages/Components/LeftSidebar/Default.cshtml
<!-- sidebar: style can be found in sidebar.less -->
<section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
        <div class="pull-left image">
            <img src="~/images/avatar3.png" class="img-circle" alt="User Image" />
        </div>
        <div class="pull-left info">
            <p>Hello, Jane</p>
            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
    </div>
    <!-- search form -->
    <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
            <input type="text" name="q" class="form-control" placeholder="Search..." />
            <span class="input-group-btn">
                <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
            </span>
        </div>
    </form>
    <!-- /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
        <li>
            <a href="/admin">
                <i class="fa fa-dashboard"></i> <span>@Strings.Dashboard</span>
            </a>
        </li>
        <li class="treeview active">
            <a href="#">
                <i class="fa fa-edit"></i> <span>@Strings.Drafts</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li class="active"><a href="general.html"><i class="fa fa-angle-double-right"></i>@Strings.DraftList</a></li>
                <li><a href="advanced.html"><i class="fa fa-angle-double-right"></i>@Strings.AddNew</a></li>
            </ul>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-tablet"></i> <span>@Strings.PublishedPosts</span>
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fa fa-trash-o"></i> <span>@Strings.Trash</span>
                <small class="badge pull-right bg-red">3</small>
            </a>
        </li>
        <li>
            <a href="../mailbox.html">
                <i class="fa fa-comments-o"></i> <span>@Strings.Comments</span>
                <small class="badge pull-right bg-yellow">12</small>
            </a>
        </li>
        <li>
            <a asp-page="/Categories/Index" asp-area="Admin">
                <i class="fa fa-list-alt"></i> <span>@Strings.Categories</span>
            </a>
        </li>
        <li>
            <a asp-page="/Tags/Index" asp-area="Admin">
                <i class="fa fa-tags"></i> <span>@Strings.Tags</span>
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fa fa-cogs"></i> <span>@Strings.Configuration</span>
            </a>
        </li>
        <li class="treeview">
            <a href="#">
                <i class="fa fa-folder"></i> <span>Examples</span>
                <i class="fa fa-angle-left pull-right"></i>
            </a>
            <ul class="treeview-menu">
                <li><a href="../examples/invoice.html"><i class="fa fa-angle-double-right"></i> Invoice</a></li>
                <li><a href="../examples/login.html"><i class="fa fa-angle-double-right"></i> Login</a></li>
                <li><a href="../examples/register.html"><i class="fa fa-angle-double-right"></i> Register</a></li>
                <li><a href="../examples/lockscreen.html"><i class="fa fa-angle-double-right"></i> Lockscreen</a></li>
                <li><a href="../examples/404.html"><i class="fa fa-angle-double-right"></i> 404 Error</a></li>
                <li><a href="../examples/500.html"><i class="fa fa-angle-double-right"></i> 500 Error</a></li>
                <li><a href="../examples/blank.html"><i class="fa fa-angle-double-right"></i> Blank Page</a></li>
            </ul>
        </li>
    </ul>
</section>
<!-- /.sidebar -->

WebBlog/WebBlog/Areas/Admin/Pages/Dashboard/Index.cshtml
@page
@model Dashboard.IndexModel
@{
    ViewData["Title"] = "Dashboard";
}

<h2>Dashboard</h2>

WebBlog/WebBlog/Areas/Admin/Pages/Login/Index.cshtml
@page
@model Login.IndexModel
@{
}

<h2>Razor pages</h2>

WebBlog/WebBlog/Areas/Admin/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>WebBlog | @ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/ionicons.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"  asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/font-awesome.min.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/css/ionicons.min.css" asp-append-version="true"/>
    </environment>
    <link rel="stylesheet" href="~/css/AdminLTE.css" />
</head>
<body class="skin-black">

    <header class="header">
        <a href="/admin" class="logo">
            <!-- Add the class icon to your logo image or logo icon to add the margining -->
            AdminLTE
        </a>
        <!-- Navigation -->
        @await Component.InvokeAsync("Navigation")
    </header>

    <div class="wrapper row-offcanvas row-offcanvas-left">
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="left-side sidebar-offcanvas">
            @await Component.InvokeAsync("LeftSidebar")
        </aside>

        <aside class="right-side">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                @await Component.InvokeAsync("Breadcrumb")
            </section>

            <section class="content">
                @RenderBody()
            </section>
        </aside>


        <hr />
        <footer>
            <p>&copy; 2018 - WebBlog</p>
        </footer>
    </div>

    <div id="confirmModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    @Strings.AreYouSure
                </div>
                <div class="modal-footer">
                    <button type="button" data-dismiss="modal" class="btn btn-primary" id="delete">@Strings.Delete</button>
                    <button type="button" data-dismiss="modal" class="btn">@Strings.Cancel</button>
                </div>
            </div>
        </div>
        
    </div>
    <environment include="Development">
        <script src="~/js/AdminLTE/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/AdminLTE/jquery.min.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script src="~/js/AdminLTE/app.js" type="text/javascript" asp-append-version="true"></script>

    <script>

        function confirmDelete(e) {
            var $url = $(e).attr('href');
            $('#confirmModal').modal({
                backdrop: 'static',
                keyboard: false
            }).one('click', '#delete', function (e) {
                document.location.href = $url;
            });

            return false;
        }
       
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebBlog/WebBlog/Areas/Admin/Pages/Tags/Index.cshtml
@page
@model IndexModel
@{
}

<style>
    form[editmode="false"] .jqEditMode,
    form[editmode="true"] .jqViewMode {
        display: none !important;
    }
</style>
<div class="col-sm-6">
    <span class="text-danger" id="errorMessages"></span>

    @foreach (var item in Model.Tags)
    {
        <div class="form-group has-feedback">
            <form asp-page-handler="Edit" method="post" editmode="false" onsubmit="return onSubmit(this)">

                <div class="input-group">
                    <input type="hidden" asp-for="@item.TagId" name="TagModel.TagId" />
                    <input type="text" asp-for="@item.TagName" name="TagModel.TagName" id="@item.TagId" asp-value="@item.TagName" class="form-control" readonly>

                    <div class="input-group-btn jqViewMode">
                        <a class="btn btn-primary" onclick="onEditForm('#@item.TagId')">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                        <a asp-page-handler="Delete" asp-route-id="@item.TagId" class="btn btn-danger" onclick="return confirmDelete(this)" >
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    </div>

                    <div class="input-group-btn jqEditMode">
                        <button class="btn btn-primary">
                            <span type="submit" class="glyphicon">@Strings.Save</span>
                        </button>
                        <a class="btn btn-default" onclick="onCancelForm('#@item.TagId')">
                            <span type="submit" class="glyphicon">@Strings.Cancel</span>
                        </a>
                    </div>
                </div>

            </form>
        </div>
    }



    <br />
    <form class="row" asp-page-handler="Add" method="post">
        <div class="col-sm-9">
            <input type="text" asp-for="@Model.TagModel.TagName" class="form-control" placeholder="Enter tag">
            <span class="text-danger" asp-validation-for="@Model.TagModel.TagName"></span>
        </div>
        <button type="submit" id="submitTag" class="btn btn-primary col-sm-3">@Strings.AddNew</button>
    </form>
</div>
<div class="clearfix"/>

@section Scripts {
    <script>
        function onCancelForm(elementId) {
            // Set back to value before edit
            $(elementId).val($(elementId).attr('asp-value'));
            $(elementId).attr('readonly', true);
            // clear error message if it occurs
            $('#errorMessages').text('');

            $(elementId).parents('form').attr('editMode', false)
        }

        function onEditForm(elementId) {
            $(elementId).removeAttr('readonly');
            $(elementId).parents('form').attr('editMode', true)
        }

        function onSubmit(e) {
            $.post('/Admin/Tags?handler=Edit', $(e).serialize())
                .done(function () {
                    window.location.reload();
                }).fail(function (xhr) {
                    $('#errorMessages').text(xhr.responseText);
                })

            return false;
        }
    </script>
    
}